FROM {{base}}
ENV ERU 1
ADD {{appname}} /{{appname}}
ADD launcher /usr/local/bin/launcher
ADD launcheroot /usr/local/bin/launcheroot
WORKDIR /{{appname}}
RUN useradd -u {{user_id}} -d /nonexistent -s /sbin/nologin -U {{appname}}
{% for build_cmd in build_cmds %}
RUN {{build_cmd|safe}}
{% endfor %}
