FROM {{base}}
ENV ERU 1
ADD {{appname}} /{{appname}}
ADD launch /usr/local/bin/launch
WORKDIR /{{appname}}
RUN useradd -u {{user_id}} -d /nonexistent -s /sbin/nologin -U {{appname}}
{% for build_cmd in build_cmds %}
RUN {{build_cmd}}
{% endfor %}
