#!/bin/sh

[ -e certs ] || mkdir certs
cd certs

openssl genrsa -aes256 -out ca-key.pem 2048
openssl req -new -x509 -days 365 -key ca-key.pem -sha256 -out ca.pem
openssl genrsa -out server-key.pem 2048

HOST=`hostname`
openssl req -subj "/CN=$HOST" -new -key server-key.pem -out server.csr

hostIP=`ifconfig em1 2>/dev/null|awk '/inet addr:/ {print $2}'|sed 's/addr://'`
echo subjectAltName = IP:$hostIP,IP:127.0.0.1 > extfile.cnf
openssl x509 -req -days 365 -in server.csr -CA ca.pem -CAkey ca-key.pem -CAcreateserial -out server-cert.pem -extfile extfile.cnf

openssl genrsa -out key.pem 2048
openssl req -subj '/CN=client' -new -key key.pem -out client.csr

echo extendedKeyUsage = clientAuth > extfile.cnf
openssl x509 -req -days 365 -in client.csr -CA ca.pem -CAkey ca-key.pem -CAcreateserial -out cert.pem -extfile extfile.cnf

rm -v client.csr server.csr ca.srl
chmod -v 0400 ca-key.pem key.pem server-key.pem
chmod -v 0444 ca.pem server-cert.pem cert.pem

[ -e /etc/docker/tls ] || mkdir -p /etc/docker/tls
cp -f ca.pem server-key.pem server-cert.pem /etc/docker/tls

[ -e /root/.docker/$hostIP ] || mkdir -p /root/.docker/$hostIP
cp -f ca.pem key.pem cert.pem /root/.docker/$hostIP

cd ..
rm -rf certs
